services:
  - type: web
    name: afrikaans-agent-mcp-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 8000
      # Add your Neo4j credentials here when ready
      # - key: NEO4J_URI
      #   value: bolt://your-neo4j-instance:7687
      # - key: NEO4J_USERNAME
      #   value: neo4j
      # - key: NEO4J_PASSWORD
      #   value: your-password 